#ifndef UART_H
#define UART_H
//usart2
#define UART_BOUNDARY 0x40004400
#define UART_RCC_BOUNDARY_ADDRESS 0x40021000

//GPIOA TX2
#define GPIO_BOUNDARY_ADDRESS 0x40010800
#define UART_CRL_OFFSET 0x0
#define UART_ODR_OFFSET 0x0C
#define IOPAEN 2

//port clock enable regigster offset
#define UART_APB1ENR_OFFSET  0x1C
#define UART_SR_OFFSET 0x00
#define UART_DR_OFFSET 0x04
#define UART_BRR_OFFSET 0x08
#define UART_CR1_OFFSET 0x0C
#define UART_CR2_OFFSET 0x10
#define UART_TE_ENABLE 3
#define UART_UE_ENABLE 13
#define UART_PCLK_BIT 11
#define UART_EN_BIT 17

#define UART_DR (UART_BOUNDARY + UART_DR_OFFSET)
#define UART_BRR (UART_BOUNDARY + UART_BRR_OFFSET)
#define UART_SR (UART_BOUNDARY + UART_SR_OFFSET)
#define UART_CR1 (UART_BOUNDARY + UART_CR1_OFFSET)
#define UART_CR2 (UART_BOUNDARY + UART_CR2_OFFSET)
#define UART_APB1ENR (UART_RCC_BOUNDARY_ADDRESS + UART_APB1ENR_OFFSET)
#endif


void initUart();
void sendData1(uint8_t data);
